### ISSUE TITLE
[R0.60] Nox Aestros cannot change directly from staff to shortsword

### ISSUE THREAD

**Issue by chris-torrence** [6502-workshop/NA#22] opened 2018-11-10 20:39 UTC
My party has 4 weapons available:
<img width="929" alt="screen shot 2018-11-10 at 1 36 49 pm" src="https://user-images.githubusercontent.com/5461379/48305758-b5022980-e4ed-11e8-994d-9717ea7d4fce.png">
If I try to change Nox Aestros directly from the Staff to Shortsword, I get a "Strength too low to wield" error. However, I can change from Staff to Shortbow, and then from Shortbow to Shortsword without errors. Same problem happens in the opposite direction, changing from Shortsword to Staff. (If it makes any difference, my strength is actually too low to use the Flatbow.)

**Comment by 6502-workshop** [comment] 2018-11-12 19:37
Hi Chris,

Thanks for reporting. I'm not able to reproduce. Do you have an image where you can reproduce the problem? 

Also, something I notice from the screenshot is that Nox Aetros has a readied equipment weight of 8, and he has a strength of 8 (unless you increased during levelup). Nox Aetros has a readied equipment weight of 4 after joining the party (staff + robes). Do you recall if you readied different armor?

**Comment by chris-torrence** [comment] 2018-11-12 23:07
My Nox Aetros is equipped with Mages Cloak, Leather Helm, Cloth Boots, Cloth Gloves. I'll send an image that reproduces the problem.

**Comment by 6502-workshop** [comment] 2018-11-13 01:53
Thanks for the image!

MY NOTES
-------------

*Using Chris's image, (Nox Aetros), as a reported, if I ready the staff, and then ready the shortsword, it say STR too low, but both have same weight so it should unready the staff and ready the shortsword.

*Using Chris's image, (Nox Aetros), if I ready the shortsword (switching from shortbow to shortsword) that works, but if I then unready the shortsword it says strength too low! Look into this case first as it's the most outside of expected parameters and might lead to the root cause for both.

**Comment by 6502-workshop** [comment] 2018-11-13 19:44
Hi Chris,

I checked into this and what's happening in this scenario is the game thinks that the player is trying to ready the shortsword in addition to the staff (i.e. dual wield).

I added a note to our manual outline (in OneNote) to mention dual wielding. 

Also, unless you can think of a better approach, I'm going to see if I can customize the "STR too low" message to say "STR too low to dual wield" 

Additionally, researching this led to be finding a different, but related issue. 

If the player has QTY 2 of a weapon, but only enough STR to wield once, the game will treat the the enter key as a ready request (to dual wield) and kick the STR too low message. This makes it impossible for the player to unready that weapon. I'm going to see if I can get the code to detect this scenario and treat it as an unready request in conjunction with with an "STR too low to dual wield" message"

**Comment by 6502-workshop** [comment] 2018-11-13 20:17
Actually I spoke too soon. It looks like I made the algorithm capable of detecting these scenarios and to adjust it's treatment of the enter keypress as ready or unready accordingly. 

I'll see if I can figure out why it's failing in this case.

**Comment by 6502-workshop** [comment] 2018-11-14 18:43
Chris,

Question for you.

In the case in the screenshot below, the player has a staff readied and 2 extra staffs available, and 1 shortswords available.

If the player presses enter on shortsword, the engine will 

1) ready the shortsword in addition to the staff (if the player has sufficient strength), OR

2) if the player doesn't have sufficient strength to ready both, then the staff will be unreadied and the shortsword will be readied.

The question is, with case #2, do you think it's helpful if the text window prints "STR too low to dual wield"? 

My thought is that it's helpful if the player was trying to dual wield but if the player was just trying to switch weapons I wonder if it would add confusion.

Thanks!


![screen shot 2018-11-14 at 12 38 32 pm](https://user-images.githubusercontent.com/19576990/48504387-403f3000-e80a-11e8-9de0-2e38ca7f6d8d.png)

**Comment by chris-torrence** [comment] 2018-11-14 23:52
I think it would be confusing to print that "STR too low to dual wield" message. It should be obvious from the asterisks that the player is wielding either 1 or 2 weapons. Also, just out of curiosity, a staff is usually a two-handed weapon?

**Comment by 6502-workshop** [comment] 2018-11-15 17:51
Ok, thanks for the perspective. I won't add the message. Good catch on the staff, thanks.

All known ready/unready corner cases are fixed for next release and staff is changed to 2-handed.

**Closed by 6502-workshop** 2018-11-15 17:51 UTC
Labels: Scheduled for work (near-term), bug
